# DNS
resolver 127.0.0.11 192.168.88.27 valid=30s ipv6=off;

client_max_body_size 10g;

# --------------------------------------------------
# HTTP → HTTPS
# --------------------------------------------------
server {
    listen 80;
    server_name *.syndicate;
    return 301 https://$host$request_uri;
}

# --------------------------------------------------
# UPSTREAM MAP
# --------------------------------------------------
map $host $upstream {
    default  "";

    proxmox.syndicate               https://192.168.88.20:8006;
    omv.syndicate                   https://192.168.88.21;
    jenkins.syndicate               https://192.168.88.95:8443;
    pikvm.syndicate                 https://192.168.88.13;

    portainer.syndicate             https://portainer:9443;
    wallos.syndicate                http://wallos;
    heimdall.syndicate              http://heimdall;
    semaphore.syndicate             http://semaphore:3000;
    nexus.syndicate                 http://nexus:8081;
    registry.syndicate              http://nexus:6000;
    it-tools.syndicate              http://it-tools;
    n8n.syndicate                   http://n8n:5678;
    grafana.syndicate               http://grafana:3000;
    prometheus.syndicate            http://prometheus:9090;
    uptime-kuma.syndicate           http://uptime-kuma:3001;
    dvr.syndicate                   http://192.168.88.19;
    vault.syndicate                 http://192.168.88.50:8200;
    nextcloud.syndicate             https://nextcloud;
}
# --------------------------------------------------
# PROXY SERVER
# --------------------------------------------------
server {
    listen 443 ssl;
    http2 on;

    server_name *.syndicate;

    resolver 127.0.0.11 valid=30s ipv6=off;
    client_max_body_size 10g;

    proxy_connect_timeout 10s;
    proxy_read_timeout    3600s;
    proxy_send_timeout    3600s;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/syndicate.key;

    if ($upstream = "") { return 444; }

    location / {
        set $target $upstream;
        if ($target = "") { return 444; }
        
        proxy_pass $target;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;


        # proxy_pass $upstream;
        proxy_redirect http:// https://;
    }

    location /v2/ {
        proxy_http_version 1.1;

        client_max_body_size 0;
        proxy_request_buffering off;
        proxy_buffering off;

        proxy_read_timeout    3600s;
        proxy_send_timeout    3600s;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_redirect off;

        proxy_pass $upstream;
    }

}

# # --------------------------------------------------
